using System;
using System.Net.NetworkInformation;

namespace SeudoBuild.Agent
{
    public static class AgentName
    {
        public static string GetRandomName()
        {
            var rand = new Random();
            return GetName(rand);
        }

        public static string GetUniqueAgentName()
        {
            int hash = GetMacAddresses().GetHashCode();
            var rand = new Random(hash);
            return GetName(rand);
        }

        static string GetName(Random rand)
        {
            var adjective = adjectives[rand.Next(0, adjectives.Length)];
            var animal = animals[rand.Next(0, animals.Length)];
            string name = $"{adjective}-{animal}";
            return name.ToLower();
        }

        static string GetMacAddresses()
        {
            string macAddresses = string.Empty;
            foreach (NetworkInterface nic in NetworkInterface.GetAllNetworkInterfaces())
            {
                macAddresses += nic.GetPhysicalAddress().ToString();
            }
            return macAddresses;
        }

        static string[] adjectives =
        {
            "affable",
            "affectionate",
            "agreeable",
            "ambitious",
            "amiable",
            "amicable",
            "amusing",
            "brave",
            "bright",
            "calm",
            "careful",
            "charming",
            "clever",
            "communicative",
            "compassionate",
            "conscientious",
            "considerate",
            "convivial",
            "courageous",
            "courteous",
            "creative",
            "decisive",
            "determined",
            "diligent",
            "diplomatic",
            "discreet",
            "dynamic",
            "easygoing",
            "electric",
            "emotional",
            "energetic",
            "enthusiastic",
            "exuberant",
            "fair-minded",
            "faithful",
            "fearless",
            "forceful",
            "frank",
            "friendly",
            "generous",
            "gentle",
            "good",
            "gregarious",
            "hard-working",
            "helpful",
            "honest",
            "humble",
            "humorous",
            "imaginative",
            "impartial",
            "independent",
            "intellectual",
            "intelligent",
            "intuitive",
            "inventive",
            "kind",
            "loving",
            "loyal",
            "modest",
            "mysterious",
            "neat",
            "optimistic",
            "passionate",
            "patient",
            "persistent",
            "pioneering",
            "philosophical",
            "placid",
            "plucky",
            "polite",
            "powerful",
            "practical",
            "quiet",
            "rational",
            "reliable",
            "reserved",
            "resourceful",
            "romantic",
            "self-confident",
            "self-disciplined",
            "sensible",
            "sensitive",
            "shy",
            "sincere",
            "sociable",
            "straightforward",
            "sympathetic",
            "thoughtful",
            "tidy",
            "tough",
            "unassuming",
            "understanding",
            "versatile",
            "warmhearted",
            "witty"
        };

        // Based on https://github.com/hzlzh/Domain-Name-List/blob/master/Animal-words.txt
        static string[] animals =
        {
            "Aardvark",
            "Albatross",
            "Alligator",
            "Alpaca",
            "Anteater",
            "Antelope",
            "Armadillo",
            "Badger",
            "Barracuda",
            "Bat",
            "Bear",
            "Beaver",
            "Bee",
            "Bison",
            "Buffalo",
            "Butterfly",
            "Camel",
            "Caribou",
            "Cat",
            "Caterpillar",
            "Cattle",
            "Cheetah",
            "Chicken",
            "Chinchilla",
            "Clam",
            "Cobra",
            "Cockroach",
            "Cod",
            "Cormorant",
            "Coyote",
            "Crab",
            "Crane",
            "Crocodile",
            "Crow",
            "Curlew",
            "Deer",
            "Dinosaur",
            "Dolphin",
            "Dotterel",
            "Dove",
            "Dragonfly",
            "Duck",
            "Dugong",
            "Dunlin",
            "Eagle",
            "Echidna",
            "Eel",
            "Elephant",
            "Elk",
            "Emu",
            "Ferret",
            "Finch",
            "Fish",
            "Flamingo",
            "Fly",
            "Fox",
            "Frog",
            "Gazelle",
            "Gerbil",
            "Giraffe",
            "Goat",
            "Goose",
            "Goldfish",
            "Gorilla",
            "Grasshopper",
            "Hamster",
            "Hedgehog",
            "Heron",
            "Herring",
            "Hippo",
            "Hornet",
            "Horse",
            "Hummingbird",
            "Jaguar",
            "Jay",
            "Jellyfish",
            "Kangaroo",
            "Koala",
            "Lark",
            "Lemur",
            "Leopard",
            "Lion",
            "Llama",
            "Lobster",
            "Loris",
            "Louse",
            "Lyrebird",
            "Magpie",
            "Mallard",
            "Manatee",
            "Marten",
            "Meerkat",
            "Mink",
            "Mole",
            "Monkey",
            "Moose",
            "Mouse",
            "Mosquito",
            "Mule",
            "Newt",
            "Octopus",
            "Opossum",
            "Oryx",
            "Ostrich",
            "Otter",
            "Owl",
            "Ox",
            "Oyster",
            "Panther",
            "Parrot",
            "Partridge",
            "Pelican",
            "Penguin",
            "Pheasant",
            "Pigeon",
            "Pony",
            "Porcupine",
            "Porpoise",
            "Quail",
            "Rabbit",
            "Raccoon",
            "Ram",
            "Raven",
            "Reindeer",
            "Rhino",
            "Salamander",
            "Salmon",
            "Sandpiper",
            "Sardine",
            "Scorpion",
            "Seahorse",
            "Seal",
            "Shark",
            "Sheep",
            "Shrew",
            "Shrimp",
            "Skunk",
            "Snail",
            "Snake",
            "Spider",
            "Squid",
            "Squirrel",
            "Starling",
            "Stingray",
            "Stork",
            "Swallow",
            "Swan",
            "Tapir",
            "Tiger",
            "Toad",
            "Trout",
            "Turkey",
            "Turtle",
            "Wallaby",
            "Walrus",
            "Weasel",
            "Whale",
            "Wolf",
            "Wolverine",
            "Wombat",
            "Woodcock",
            "Woodpecker",
            "Worm",
            "Yak",
            "Zebra"
        };
    }
}
